"""empty message

Revision ID: 07532dae652a
Revises: 5e97920ca814
Create Date: 2023-06-25 15:57:42.593360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07532dae652a'
down_revision = '5e97920ca814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###
