"""empty message

Revision ID: d645403c8699
Revises: da145fa763d8
Create Date: 2023-06-24 23:24:59.639817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd645403c8699'
down_revision = 'da145fa763d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_projects_user_id_project_id_key', ['user_id', 'project_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.drop_constraint('user_projects_user_id_project_id_key', type_='unique')

    # ### end Alembic commands ###
